// client/src/components/Navbar.tsx
/*
 * Genera Software — Navbar
 * Brand: Teal (#003E45), Genera Gold (#FFA800), Poppins headings, Inter body
 * Logo: Real Genera paw icon image + "GENERA" bold + "A Better Breed of Software" tagline
 */
import { useState, useEffect } from "react";
import { Link, useLocation } from "wouter";
import { Menu, X } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

const LOGO_URL =
  "https://d2xsxph8kpxj0f.cloudfront.net/310519663478487775/BxxxoQYbhf7FnKvPttwktS/genera-paw-fixed_92730de9.png";

const APP_URL = "https://app.generasoftware.com/admin";

const navLinks = [
  { href: "/", label: "Home" },
  { href: "/features", label: "Features" },
  { href: "/our-story", label: "Our Story" },
  { href: "/blog", label: "Blog" },
  { href: "/faq", label: "FAQs" },
  { href: "/contact", label: "Contact" },
];

export default function Navbar() {
  const [location] = useLocation();
  const [mobileOpen, setMobileOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 20);
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  useEffect(() => {
    setMobileOpen(false);
  }, [location]);

  return (
    <header
      className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${
        scrolled
          ? "bg-white/95 backdrop-blur-md shadow-sm"
          : "bg-white/80 backdrop-blur-sm"
      }`}
    >
      <nav className="container flex items-center justify-between h-16 lg:h-18">
        {/* Logo */}
        <Link href="/" className="flex items-center gap-2.5 group">
          <img
            src={LOGO_URL}
            alt="Genera paw logo"
            className="w-10 h-10 object-contain"
          />
          <div className="flex flex-col leading-none">
            <span
              className="text-forest text-lg tracking-wide"
              style={{ fontFamily: "var(--font-heading)", fontWeight: 800 }}
            >
              GENERA
            </span>
            <span
              className="text-[9px] text-charcoal/50 tracking-wider hidden sm:block"
              style={{ fontFamily: "var(--font-sans)" }}
            >
              A Better Breed of Software
            </span>
          </div>
        </Link>

        {/* Desktop nav */}
        <ul className="hidden lg:flex items-center gap-7">
          {navLinks.map((link) => (
            <li key={link.href}>
              <Link
                href={link.href}
                className={`text-sm font-medium transition-colors duration-200 relative py-1 ${
                  location === link.href
                    ? "text-forest"
                    : "text-charcoal/70 hover:text-forest"
                }`}
              >
                {link.label}
                {location === link.href && (
                  <motion.span
                    layoutId="nav-underline"
                    className="absolute bottom-0 left-0 right-0 h-0.5 bg-gold rounded-full"
                  />
                )}
              </Link>
            </li>
          ))}
        </ul>

        {/* Desktop CTA */}
        <div className="hidden lg:flex items-center gap-3">
          <a
            href={APP_URL}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center justify-center px-5 py-2.5 bg-gold text-forest text-sm font-bold rounded-lg hover:bg-gold-dark transition-all duration-200 shadow-sm hover:shadow-md"
            style={{ fontFamily: "var(--font-heading)" }}
          >
            Start 3-Month Free Trial
          </a>
        </div>

        {/* Mobile toggle */}
        <button
          onClick={() => setMobileOpen(!mobileOpen)}
          className="lg:hidden p-2 text-charcoal"
          aria-label="Toggle menu"
        >
          {mobileOpen ? <X size={24} /> : <Menu size={24} />}
        </button>
      </nav>

      {/* Mobile menu */}
      <AnimatePresence>
        {mobileOpen && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: "auto" }}
            exit={{ opacity: 0, height: 0 }}
            transition={{ duration: 0.25 }}
            className="lg:hidden bg-white border-t border-border overflow-hidden"
          >
            <div className="container py-4 flex flex-col gap-1">
              {navLinks.map((link) => (
                <Link
                  key={link.href}
                  href={link.href}
                  className={`py-3 px-3 rounded-lg text-base font-medium transition-colors ${
                    location === link.href
                      ? "text-forest bg-gold-light"
                      : "text-charcoal hover:bg-light-grey"
                  }`}
                >
                  {link.label}
                </Link>
              ))}
              <div className="pt-3 mt-2 border-t border-border flex flex-col gap-2">
                <a
                  href={APP_URL}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="py-3 px-3 text-center bg-gold text-forest font-bold rounded-lg"
                  style={{ fontFamily: "var(--font-heading)" }}
                >
                  Start 3-Month Free Trial
                </a>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </header>
  );
}

// src/lib/Navbar.svelte
<script>
  import { onMount } from "svelte";

  let mobileOpen = false;
  let scrolled = false;

  const navLinks = [
    { label: "Home", href: "/" },
    { label: "Features", href: "/#features" },
    { label: "Our Story", href: "/our-story" },
    { label: "Blog", href: "/blog" },
    { label: "FAQ", href: "/faq" },
    { label: "Contact", href: "/#contact" },
  ];

  onMount(() => {
    const onScroll = () => {
      scrolled = window.scrollY > 12;
    };
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  });
</script>

<div class="fixed top-0 left-0 right-0 z-[999] flex flex-col items-center pointer-events-none">
  <div class="h-4 shrink-0"></div>

  <nav
    role="banner"
    class="pointer-events-auto relative overflow-visible
      w-[calc(100%-5rem)] max-[860px]:w-[calc(100%-2rem)] max-w-[58rem]
      backdrop-blur-[20px] backdrop-saturate-[1.6]
      border
      transition-[box-shadow,border-color,background,border-radius] duration-300 ease-in-out
      {scrolled
      ? 'bg-[#fdfde9] border-black/10'
      : 'bg-[#fdfde9] border-black/10'}
      {mobileOpen ? 'rounded-t-full rounded-b-3xl' : 'rounded'}">
    <div class="flex items-center px-5 h-15 gap-2">
      <!-- Brand -->
      <a href="/" id="w-node-nav-brand" class="flex items-center gap-2 no-underline shrink-0 mr-2" aria-label="Genera Home">
        <img src="/genera-logo.svg" loading="eager" alt="Genera Logo" class="w-6.5 h-6.5 object-contain" />
        <span class="text-[0.9375rem] font-extrabold tracking-[0.08em] text-[#1a1a1a]">GENERA</span>
      </a>

      <!-- Desktop links -->
      <ul class="flex items-center list-none m-0 p-0 flex-1 justify-center max-[860px]:hidden" role="list">
        {#each navLinks as link}
          <li>
            <a
              href={link.href}
              class="block px-[0.7rem] py-1.5 text-[0.8125rem] font-medium text-[#2d2d2d] no-underline rounded-full whitespace-nowrap transition-[color,background] duration-150 ease-in-out hover:text-black hover:bg-black/5"
              >{link.label}</a>
          </li>
        {/each}
      </ul>

      <!-- Right: CTAs + hamburger -->
      <div class="flex items-center gap-2 shrink-0 ml-2">
        <a
          id="nav-login-link"
          href="https://app.generasoftware.com/admin"
          class="inline-flex items-center px-[0.9rem] py-[0.4rem] border-[1.5px] border-black/20 rounded-full text-[0.8125rem] font-semibold text-[#1a1a1a] no-underline whitespace-nowrap bg-transparent transition-[border-color,background] duration-150 ease-in-out hover:border-black/40 hover:bg-black/[0.03] max-[860px]:hidden"
          target="_blank"
          rel="noopener noreferrer">Log in</a>
        <a
          id="nav-signup-cta"
          href="https://app.generasoftware.com/admin"
          class="inline-flex items-center px-4 py-[0.4rem] bg-[#003B46] border-[1.5px] border-[#003B46] rounded-full text-[0.8125rem] font-semibold text-white no-underline whitespace-nowrap transition-[background,transform,box-shadow] duration-150 ease-in-out hover:bg-[#025262] hover:border-[#025262] hover:-translate-y-px hover:shadow-[0_3px_10px_rgba(0,59,70,0.28)] max-[860px]:hidden"
          target="_blank"
          rel="noopener noreferrer">Sign Up Free</a>

        <button
          class="hidden max-[860px]:flex flex-col justify-center items-center gap-1 w-8 h-8 bg-transparent border-none cursor-pointer p-1 rounded-full transition-[background] duration-150 ease-in-out hover:bg-black/5"
          on:click={() => (mobileOpen = !mobileOpen)}
          aria-label={mobileOpen ? "Close navigation" : "Open navigation"}
          aria-expanded={mobileOpen}>
          <span class="block w-4.5 h-[1.5px] bg-[#1a1a1a] rounded-[2px] origin-center transition-[transform,opacity] duration-[250ms] ease-in-out {mobileOpen ? 'translate-y-[5.5px] rotate-45' : ''}"></span>
          <span class="block w-4.5 h-[1.5px] bg-[#1a1a1a] rounded-[2px] origin-center transition-[transform,opacity] duration-[250ms] ease-in-out {mobileOpen ? 'opacity-0 scale-x-0' : ''}"></span>
          <span class="block w-4.5 h-[1.5px] bg-[#1a1a1a] rounded-[2px] origin-center transition-[transform,opacity] duration-[250ms] ease-in-out {mobileOpen ? '-translate-y-[5.5px] -rotate-45' : ''}"></span>
        </button>
      </div>
    </div>

    <!-- Mobile menu -->
    {#if mobileOpen}
      <div class="border-t border-black/[0.06] animate-[slideDown_0.18s_ease] min-[861px]:hidden" role="navigation" aria-label="Mobile navigation">
        <ul role="list" class="list-none m-0 px-4 pt-2 pb-3.5 flex flex-col gap-0.5">
          {#each navLinks as link}
            <li>
              <a
                href={link.href}
                class="block px-3 py-2.5 text-[0.9375rem] font-medium text-[#1a1a1a] no-underline rounded-lg transition-[background] duration-[120ms] ease-in-out hover:bg-black/5"
                on:click={() => (mobileOpen = false)}>{link.label}</a>
            </li>
          {/each}
          <li class="h-px bg-black/[0.06] my-1.5 mx-3"></li>
          <li>
            <a
              href="https://app.generasoftware.com/admin"
              class="block p-3 text-center bg-[#003B46] text-white text-[0.9375rem] font-semibold no-underline rounded-xl transition-[background] duration-150 ease-in-out hover:bg-[#025262]"
              target="_blank"
              rel="noopener noreferrer"
              on:click={() => (mobileOpen = false)}>Sign Up Free</a>
          </li>
        </ul>
      </div>
    {/if}

    <!-- Decorative lines -->
    <div class="absolute top-1/2 -translate-y-1/2 right-13 w-px h-4.5 bg-black/10 pointer-events-none max-[860px]:hidden"></div>
  </nav>
</div>

<style>
  @keyframes slideDown {
    from {
      opacity: 0;
      transform: translateY(-4px);
    }
    to {
      opacity: 1;
      transform: translateY(0);
    }
  }
</style>
