// src/lib/Navbar.svelte
<script>
  import { onMount } from "svelte";

  let mobileOpen = false;
  let scrolled = false;

  const navLinks = [
    { label: "Home", href: "/" },
    { label: "Features", href: "/#features" },
    { label: "Our Story", href: "/our-story" },
    { label: "Blog", href: "/blog" },
    { label: "FAQ", href: "/faq" },
    { label: "Contact", href: "/#contact" },
  ];

  onMount(() => {
    const onScroll = () => {
      scrolled = window.scrollY > 12;
    };
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  });
</script>

<div class="fixed top-0 left-0 right-0 z-[999] flex flex-col items-center pointer-events-none">
  <div class="h-4 shrink-0"></div>

  <nav
    role="banner"
    class="pointer-events-auto relative overflow-visible
      w-[calc(100%-5rem)] max-[860px]:w-[calc(100%-2rem)] max-w-[58rem]
      backdrop-blur-[20px] backdrop-saturate-[1.6]
      border
      transition-[box-shadow,border-color,background,border-radius] duration-300 ease-in-out
      {scrolled
      ? 'bg-[#fdfde9] border-black/10'
      : 'bg-[#fdfde9] border-black/10'}
      {mobileOpen ? 'rounded-t-full rounded-b-3xl' : 'rounded'}">
    <div class="flex items-center px-5 h-15 gap-2">
      <!-- Brand -->
      <a href="/" id="w-node-nav-brand" class="flex items-center gap-2 no-underline shrink-0 mr-2" aria-label="Genera Home">
        <img src="/genera-logo.svg" loading="eager" alt="Genera Logo" class="w-6.5 h-6.5 object-contain" />
        <span class="text-[0.9375rem] font-extrabold tracking-[0.08em] text-[#1a1a1a]">GENERA</span>
      </a>

      <!-- Desktop links -->
      <ul class="flex items-center list-none m-0 p-0 flex-1 justify-center max-[860px]:hidden" role="list">
        {#each navLinks as link}
          <li>
            <a
              href={link.href}
              class="block px-[0.7rem] py-1.5 text-[0.8125rem] font-medium text-[#2d2d2d] no-underline rounded-full whitespace-nowrap transition-[color,background] duration-150 ease-in-out hover:text-black hover:bg-black/5"
              >{link.label}</a>
          </li>
        {/each}
      </ul>

      <!-- Right: CTAs + hamburger -->
      <div class="flex items-center gap-2 shrink-0 ml-2">
        <a
          id="nav-login-link"
          href="https://app.generasoftware.com/admin"
          class="inline-flex items-center px-[0.9rem] py-[0.4rem] border-[1.5px] border-black/20 rounded-full text-[0.8125rem] font-semibold text-[#1a1a1a] no-underline whitespace-nowrap bg-transparent transition-[border-color,background] duration-150 ease-in-out hover:border-black/40 hover:bg-black/[0.03] max-[860px]:hidden"
          target="_blank"
          rel="noopener noreferrer">Log in</a>
        <a
          id="nav-signup-cta"
          href="https://app.generasoftware.com/admin"
          class="inline-flex items-center px-4 py-[0.4rem] bg-[#003B46] border-[1.5px] border-[#003B46] rounded-full text-[0.8125rem] font-semibold text-white no-underline whitespace-nowrap transition-[background,transform,box-shadow] duration-150 ease-in-out hover:bg-[#025262] hover:border-[#025262] hover:-translate-y-px hover:shadow-[0_3px_10px_rgba(0,59,70,0.28)] max-[860px]:hidden"
          target="_blank"
          rel="noopener noreferrer">Sign Up Free</a>

        <button
          class="hidden max-[860px]:flex flex-col justify-center items-center gap-1 w-8 h-8 bg-transparent border-none cursor-pointer p-1 rounded-full transition-[background] duration-150 ease-in-out hover:bg-black/5"
          on:click={() => (mobileOpen = !mobileOpen)}
          aria-label={mobileOpen ? "Close navigation" : "Open navigation"}
          aria-expanded={mobileOpen}>
          <span class="block w-4.5 h-[1.5px] bg-[#1a1a1a] rounded-[2px] origin-center transition-[transform,opacity] duration-[250ms] ease-in-out {mobileOpen ? 'translate-y-[5.5px] rotate-45' : ''}"></span>
          <span class="block w-4.5 h-[1.5px] bg-[#1a1a1a] rounded-[2px] origin-center transition-[transform,opacity] duration-[250ms] ease-in-out {mobileOpen ? 'opacity-0 scale-x-0' : ''}"></span>
          <span class="block w-4.5 h-[1.5px] bg-[#1a1a1a] rounded-[2px] origin-center transition-[transform,opacity] duration-[250ms] ease-in-out {mobileOpen ? '-translate-y-[5.5px] -rotate-45' : ''}"></span>
        </button>
      </div>
    </div>

    <!-- Mobile menu -->
    {#if mobileOpen}
      <div class="border-t border-black/[0.06] animate-[slideDown_0.18s_ease] min-[861px]:hidden" role="navigation" aria-label="Mobile navigation">
        <ul role="list" class="list-none m-0 px-4 pt-2 pb-3.5 flex flex-col gap-0.5">
          {#each navLinks as link}
            <li>
              <a
                href={link.href}
                class="block px-3 py-2.5 text-[0.9375rem] font-medium text-[#1a1a1a] no-underline rounded-lg transition-[background] duration-[120ms] ease-in-out hover:bg-black/5"
                on:click={() => (mobileOpen = false)}>{link.label}</a>
            </li>
          {/each}
          <li class="h-px bg-black/[0.06] my-1.5 mx-3"></li>
          <li>
            <a
              href="https://app.generasoftware.com/admin"
              class="block p-3 text-center bg-[#003B46] text-white text-[0.9375rem] font-semibold no-underline rounded-xl transition-[background] duration-150 ease-in-out hover:bg-[#025262]"
              target="_blank"
              rel="noopener noreferrer"
              on:click={() => (mobileOpen = false)}>Sign Up Free</a>
          </li>
        </ul>
      </div>
    {/if}

    <!-- Decorative lines -->
    <div class="absolute top-1/2 -translate-y-1/2 right-13 w-px h-4.5 bg-black/10 pointer-events-none max-[860px]:hidden"></div>
  </nav>
</div>

<style>
  @keyframes slideDown {
    from {
      opacity: 0;
      transform: translateY(-4px);
    }
    to {
      opacity: 1;
      transform: translateY(0);
    }
  }
</style>

// components/Navbar.tsx
"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import BookDemoButton from "@/components/BookDemoButton";
import { LOGIN_URL } from "@/lib/urls";

const NAV_LINKS = [
  { href: "/", label: "Home" },
  { href: "/features", label: "Features" },
  { href: "/our-story", label: "Our Story" },
  { href: "/blog", label: "Blog" },
  { href: "/faqs", label: "FAQs" },
  { href: "/contact", label: "Contact" },
] as const;

const PAW_LOGO = "/images/genera-svg.svg";

export default function Navbar() {
  const [stuck, setStuck] = useState(false);
  const [open, setOpen] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);
  const hamRef = useRef<HTMLButtonElement>(null);

  useEffect(() => {
    const onScroll = () => setStuck(window.scrollY > 50);
    onScroll();
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  useEffect(() => {
    if (!open) return;
    const onClick = (e: MouseEvent) => {
      const target = e.target as Node;
      if (
        menuRef.current?.contains(target) ||
        hamRef.current?.contains(target)
      ) {
        return;
      }
      setOpen(false);
    };
    const onHide = () => setOpen(false);
    document.addEventListener("click", onClick);
    document.addEventListener("visibilitychange", onHide);
    window.addEventListener("pagehide", onHide);
    return () => {
      document.removeEventListener("click", onClick);
      document.removeEventListener("visibilitychange", onHide);
      window.removeEventListener("pagehide", onHide);
    };
  }, [open]);

  return (
    <>
      <nav
        className={`sticky top-0 z-[100] bg-forest px-8 transition-shadow duration-300 ${
          stuck ? "shadow-[0_4px_24px_rgba(0,0,0,0.18)]" : ""
        }`}
      >
        <div className="mx-auto flex h-[68px] max-w-[1160px] items-center gap-8">
          <Link
            href="/"
            aria-label="Genera home"
            className="flex shrink-0 items-center gap-2.5"
          >
            <Image
              src={PAW_LOGO}
              alt="Genera paw logo"
              width={38}
              height={38}
              className="h-[38px] w-[38px] object-contain"
              priority
            />
            <span className="flex flex-col leading-[1.1]">
              <span className="font-poppins text-[1.1rem] font-extrabold tracking-[0.125rem] text-white">
                GENERA
              </span>
              <span className="text-[0.62rem] tracking-[0.5px] text-white/60">
                A Better Breed of Software
              </span>
            </span>
          </Link>

          <div className="mx-auto hidden items-center gap-1 md:flex">
            {NAV_LINKS.map((l) => (
              <Link
                key={l.href}
                href={l.href}
                className="rounded-[20px] px-3 py-1.5 text-[0.9rem] font-medium text-white/80 transition-colors hover:bg-white/10 hover:text-white"
              >
                {l.label}
              </Link>
            ))}
          </div>

          <div className="hidden items-center gap-2 md:flex">
            <Link
              href={LOGIN_URL}
              className="rounded-full px-3 py-1.5 text-[0.85rem] font-medium text-white/80 transition-colors hover:bg-white/10 hover:text-white"
            >
              Login
            </Link>
            <BookDemoButton
              className="inline-flex items-center rounded-full bg-gold px-5 py-2 font-poppins text-[0.85rem] font-bold text-ink shadow-[0_4px_14px_rgba(255,168,0,0.35)] transition-shadow hover:shadow-[0_6px_22px_rgba(255,168,0,0.5)]"
            >
              Join Genera
            </BookDemoButton>
          </div>

          <button
            ref={hamRef}
            type="button"
            aria-label="Open menu"
            aria-expanded={open}
            onClick={() => setOpen((v) => !v)}
            className="ml-auto flex flex-col gap-[5px] p-1.5 md:hidden"
          >
            <span
              className={`block h-[2.5px] w-6 rounded bg-white transition-transform ${
                open ? "translate-y-[7.5px] rotate-45" : ""
              }`}
            />
            <span
              className={`block h-[2.5px] w-6 rounded bg-white transition-opacity ${
                open ? "opacity-0" : ""
              }`}
            />
            <span
              className={`block h-[2.5px] w-6 rounded bg-white transition-transform ${
                open ? "-translate-y-[7.5px] -rotate-45" : ""
              }`}
            />
          </button>
        </div>
      </nav>

      <div
        ref={menuRef}
        className={`fixed inset-0 z-[99] flex-col gap-2 bg-forest px-8 pt-20 pb-8 ${
          open ? "flex" : "hidden"
        } md:hidden`}
      >
        <button
          type="button"
          onClick={() => setOpen(false)}
          aria-label="Close menu"
          className="absolute right-6 top-4 cursor-pointer border-none bg-transparent text-3xl font-light leading-none text-white"
        >
          ×
        </button>
        {NAV_LINKS.map((l) => (
          <Link
            key={l.href}
            href={l.href}
            onClick={() => setOpen(false)}
            className="border-b border-white/10 py-3 font-poppins text-[1.35rem] font-bold text-white/85 hover:text-gold"
          >
            {l.label}
          </Link>
        ))}
        <div className="mt-6 flex flex-col gap-3">
          <BookDemoButton
            className="btn btn-gold btn-lg"
            onClick={() => setOpen(false)}
          />
          <Link
            href={LOGIN_URL}
            className="btn btn-outline-w btn-lg"
            onClick={() => setOpen(false)}
          >
            Login
          </Link>
        </div>
      </div>
    </>
  );
}
